import 'package:pd/files/course.dart';

List<Course> allCourses = [
      Course(
        title: "UIUX Designing - Advanced",
        category: "Designs",
        imageUrl: 'assets/images/c1.png',
        rate: 5999,
        orgRate: 10999,
        rating: 4.5,
        enrolledAspirants: 1356,
      ),
      Course(
        title: "React JS -Beginners",
        category: "Development",
        imageUrl: 'assets/images/c2.png',
        rate: 3999,
        orgRate: 9999,
        rating: 4.5,
        enrolledAspirants: 1356,
      ),
      Course(
        title: "AI & ML -Beginners",
        category: "Data Science",
        imageUrl: 'assets/images/c3.png',
        rate: 3999,
        orgRate: 9999,
        rating: 4.5,
        enrolledAspirants: 1356,
      ),
      Course(
        title: "UIUX Development -Advanced",
        category: "Development",
        imageUrl: 'assets/images/c4.png',
        rate: 3999,
        orgRate: 9999,
        rating: 4.5,
        enrolledAspirants: 1356,
      ),
      Course(
        title: "UX Researcher -Beginners",
        category: "Designs",
        imageUrl: 'assets/images/c5.png',
        rate: 3999,
        orgRate: 9999,
        rating: 4.5,
        enrolledAspirants: 1356,
      ),
      Course(
        title: "Graphics Designing -Basic",
        category: "Graphic Designing",
        imageUrl: 'assets/images/c6.png',
        rate: 3999,
        orgRate: 9999,
        rating: 4.5,
        enrolledAspirants: 1356,
      ),
      Course(
        title: "SEO & Ranking",
        category: "Digital Marketing",
        imageUrl: 'assets/images/c7.png',
        rate: 3999,
        orgRate: 9999,
        rating: 4.5,
        enrolledAspirants: 1356,
      ),
    ];